const styles = {
    black: 30,
    red: 31,
    green: 32,
    yellow: 33,
    blue: 34,
    magenta: 35,
    cyan: 36,
    white: 37,
    gray: 90,
    blackBright: 90,
    redBright: 91,
    greenBright: 92,
    yellowBright: 93,
    blueBright: 94,
    magentaBright: 95,
    cyanBright: 96,
    whiteBright: 97,
    bgBlack: 40,
    bgRed: 41,
    bgGreen: 42,
    bgYellow: 43,
    bgBlue: 44,
    bgMagenta: 45,
    bgCyan: 46,
    bgWhite: 47,
    bgBlackBright: 100,
    bgRedBright: 101,
    bgGreenBright: 102,
    bgYellowBright: 103,
    bgBlueBright: 104,
    bgMagentaBright: 105,
    bgCyanBright: 106,
    bgWhiteBright: 107,
    bgGray: 100,
    bgGrey: 100
}

const sStyles = {
    '&0': 'black',
    '&1': 'blue',
    '&2': 'green',
    '&3': 'cyan',
    '&4': 'red',
    '&5': 'magenta',
    '&6': 'yellow',
    '&7': 'blackBright',
    '&8': 'whiteBright',
    '&9': 'blueBright',
    '&a': 'greenBright',
    '&b': 'cyanBright',
    '&c': 'redBright',
    '&d': 'magentaBright',
    '&e': 'yellowBright',
    '&f': 'white',
    '&!0': 'bgBlack',
    '&!1': 'bgBlue',
    '&!2': 'bgGreen',
    '&!3': 'bgCyan',
    '&!4': 'bgRed',
    '&!5': 'bgMagenta',
    '&!6': 'bgYellow',
    '&!7': 'bgBlackBright',
    '&!8': 'bgWhiteBright',
    '&!9': 'bgBlueBright',
    '&!a': 'bgGreenBright',
    '&!b': 'bgCyanBright',
    '&!c': 'bgRedBright',
    '&!d': 'bgMagentaBright',
    '&!e': 'bgYellowBright',
    '&!f': 'bgWhite',
}

module.exports = (code) => styles[sStyles[code]];