const colorCodes = {
    black: 30,
    red: 31,
    green: 32,
    yellow: 33,
    blue: 34,
    magenta: 35,
    cyan: 36,
    white: 37,
    gray: 90,
    brightBlack: 90,
    brightRed: 91,
    brightGreen: 92,
    brightYellow: 93,
    brightBlue: 94,
    brightMagenta: 95,
    brightCyan: 96,
    brightWhite: 97,
    backgroundBlack: 40,
    backgroundRed: 41,
    backgroundGreen: 42,
    backgroundYellow: 43,
    backgroundBlue: 44,
    backgroundMagenta: 45,
    backgroundCyan: 46,
    backgroundWhite: 47,
    brightBackgroundBlack: 100,
    brightBackgroundRed: 101,
    brightBackgroundGreen: 102,
    brightBackgroundYellow: 103,
    brightBackgroundBlue: 104,
    brightBackgroundMagenta: 105,
    brightBackgroundCyan: 106,
    brightBackgroundWhite: 107,
    backgroundGray: 100,
    backgroundGrey: 100,
};

const shorthandToColor = {
    '&0': 'black',
    '&1': 'blue',
    '&2': 'green',
    '&3': 'cyan',
    '&4': 'red',
    '&5': 'magenta',
    '&6': 'yellow',
    '&7': 'brightBlack',
    '&8': 'brightWhite',
    '&9': 'brightBlue',
    '&a': 'brightGreen',
    '&b': 'brightCyan',
    '&c': 'brightRed',
    '&d': 'brightMagenta',
    '&e': 'brightYellow',
    '&f': 'white',
    '&!0': 'backgroundBlack',
    '&!1': 'backgroundBlue',
    '&!2': 'backgroundGreen',
    '&!3': 'backgroundCyan',
    '&!4': 'backgroundRed',
    '&!5': 'backgroundMagenta',
    '&!6': 'backgroundYellow',
    '&!7': 'brightBackgroundBlack',
    '&!8': 'brightBackgroundWhite',
    '&!9': 'brightBackgroundBlue',
    '&!a': 'brightBackgroundGreen',
    '&!b': 'brightBackgroundCyan',
    '&!c': 'brightBackgroundRed',
    '&!d': 'brightBackgroundMagenta',
    '&!e': 'brightBackgroundYellow',
    '&!f': 'backgroundWhite',
};

module.exports = (shorthandCode) => colorCodes[shorthandToColor[shorthandCode]];
